# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Howe Lab"
title:              "The cake lab "
description:        "this is a page for Cristopher J. Howe lab, at the University of Cambridge"


# URL
url:                https://cjhowelab.github.io/home/
baseurl:            https://cjhowelab.github.io/home/
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "research"
    href:           "https://cjhowelab.github.io/home/about"
  - name:           "publications"
    href:           "https://cjhowelab.github.io/home/publication"
  - name:           "people"
    href:           "https://cjhowelab.github.io/home/people"
  - name:           "blog"
    href:           "https://cjhowelab.github.io/home/blog"
  - name:           "resources"
    href:           "https://cjhowelab.github.io/home/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
